/*
 * Stoatworks Labs - About window data for Wipe.
 *
 * PROVISIONAL HAND COPY, adapted from genlock's on 2026-09-23. Everywhere else
 * in the fleet this file is GENERATED by
 * stoatworks-backend/scripts/sync-about.py from the website's projects.json --
 * but wipe is not in projects.json yet, because it is a new repo with no
 * page. Register it and re-run the sync, and this becomes generated like the
 * rest. Until then the facts here are asserted by hand, `guide` is empty
 * because no user guide exists, and the project page it links to does not
 * exist either. graticule and genlock shipped their v0.1.0 the same way.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Wipe";
    inline constexpr auto slug = "wipe";
    inline constexpr auto hook = "A vision mixer's analogue pattern generator for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/wipe/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/wipe";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
